on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

name: Render and Publish

permissions:
    contents: write
    pages: write

jobs:
    codespell:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: codespell-project/actions-codespell@master

    build-deploy:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4
            - uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                packages: libssl-dev

            - uses: r-lib/actions/setup-r@v2
            - uses : r-lib/actions/setup-pandoc@v1
            - uses: r-lib/actions/setup-r-dependencies@v2
              with:
                r-version: '4.1.0'
                pandoc-version: '2.14'
                extra-packages: |
                    any::pagedown
                    any::posterdown

            - name: Build the poster
              run: make all && mkdir website && mv poster.html website/

            - name: Commit poster PDF
              uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
              with:
                add: 'poster.pdf'
                author_name: 'GitHub Actions'
                message: 'Add poster.pdf at ${{ github.sha }}'

            - name: Deploy html to gh-pages
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                branch: gh-pages
                folder: ${{github.workspace}}/website