on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

name: Render and Publish

permissions:
    contents: write
    pages: write

jobs:
    codespell:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: codespell-project/actions-codespell@master

    build-deploy:
        runs-on: ubuntu-latest
        container:
            image: rocker/r-rmd:latest
        steps:

            - name: Check out repository
              uses: actions/checkout@v4

            - name: Build the poster
              run: make install && make all